### ISSUE TITLE
Issue with Mongo Db 

### ISSUE THREAD

**Issue by SagarGupta1** [pa11y/pa11y-webservice#115]
Hi,
I am getting following error while running the webservice:

(node:39060) UnhandledPromiseRejectionWarning: MongoError: user is not allowed to do action [listIndexes] on [pa11y-webservice-dev.results]

**Comment by josebolos** [comment]
Hi @SagarGupta1,

You don't specify which version of pa11y-webservice and MongoDB you are using so, since there's been quite a few releases of both since this issue was created I'm going to assume that this is not a problem any more.

If you're still experiencing this issue with the latest version of webservice please feel free to reopen this issue.
